import SwiftUI

let texts = [
       "If you’d like, you can close your eyes and allow yourself to settle into this moment.",
       "Let your body soften just a little… and take a gentle breath—no need to change anything, just noticing your inhale and exhale.",
       "Now, bring awareness to your hands. Feel their warmth, their presence, the gentle contact with your body.",
       "Perhaps you can imagine them as kind, caring hands—offering comfort, support, and understanding.",
       "What would it be like to receive this touch with an open heart?",
       "What if, just for a moment, you allowed yourself to be held in this gentle kindness, without resistance or hesitation?",
       "You might even picture someone you love placing their hands there, offering the same warmth and care.",
       "Or simply recognize that this gesture is coming from you—to you. A quiet offering of kindness, no expectations, no demands.",
       "Can you let yourself receive this small act of care as you would accept a gift from a dear friend?",
       "Can you allow yourself to be worthy of this moment, just as you are?",
       "Picture yourself as someone truly deserving of compassion—because you are.",
       "Just like every human being, you deserve care, understanding, and gentleness.",
       "There is nothing you need to prove… nothing you need to earn. Right here, in this moment, you are enough.",
       "What if, instead of judging yourself, you simply offered understanding?",
       "What if, instead of pushing through, you allowed yourself to pause?",
       "This small act of kindness is always available to you.",
       "Whether you’re sitting quietly at home, in the middle of a busy day, or moving through the world… you can return to this gentle touch whenever you need a moment of support.",
       "How does it feel to offer yourself this moment of comfort?",
       "What do you notice in your body as you do? Is there warmth, a sense of ease—or maybe just the simple awareness of being here?",
       "If it feels right, you can explore different forms of touch. A light, soothing hold. A gentle press. A slow movement of your hands as if offering reassurance.",
       "What feels most comforting in this moment? And if something doesn’t feel quite right, can you give yourself permission to adjust or let it go?",
       "There is nothing to force… nothing to fix… just a quiet moment of connection with yourself.",
       "A moment of allowing… a moment of being.",
       "What would it be like to carry this sense of care with you throughout the day?",
       "To return to it when you need a reminder that you are not alone, that you are worthy of kindness?",
       "Let yourself rest in this space, even if just for a few breaths.",
       "And when you’re ready… gently release your hands… knowing that this sense of warmth and care is always within reach.",
       "You can return to it anytime… like a soft whisper of kindness… reminding you that you are worthy of love and compassion, just as you are."
   ]
