import SwiftUI

struct Instruction {
    var id: Int
    var position: (x: CGFloat, y: CGFloat)
    var text: String
    var duration: Double
}

let instructions: [Instruction] = [
    Instruction(id: 1, position: (0,0), text: "So now, we're going to practice together.", duration: 5),
    Instruction(id: 2, position: (0,0), text: "And please, try to follow along.", duration: 5),
    Instruction(id: 3, position: (0.6,0.15), text: "Just begin by bringing one hand up to your cheek and cradling your face in your hands.", duration: 5),
    Instruction(id: 4, position: (0.6,0.15), text: "You can close your eyes if you like, so that you can pay attention to what’s happening in your body.", duration: 5),
    Instruction(id: 5, position: (0.6,0.15), text: "Just feeling the contact of this hand.", duration: 5),
    Instruction(id: 6, position: (0.25,0.3), text: "Move your hands up a little bit to your shoulders.", duration: 5),
    Instruction(id: 7, position: (0.25,0.3), text: "Just resting gently on your shoulders, and notice—how does this feel?", duration: 5),
    Instruction(id: 8, position: (0,0), text: "Bring your arms down.", duration: 5),
    Instruction(id: 9, position: (0,0), text: "If you like, you can move your hand a little bit, imagining that this person is a human being who needs and deserves understanding and compassion.", duration: 5),
    Instruction(id: 10, position: (0.55,0.35), text: "Continue by bringing up one of your hands and placing it gently over your heart space.", duration: 5),
    Instruction(id: 11, position: (0.55,0.35), text: "What does it feel like when you put a hand over your heart?", duration: 5),
    Instruction(id: 12, position: (0.55,0.35), text: "Now bring up your other hand, placing it on top of the first hand, or next to it if that feels more comfortable.", duration: 5),
    Instruction(id: 13, position: (0.55,0.35), text: "Just taking a moment to feel these two hands, perhaps imagining that they are caring hands, offering kindness and warmth.", duration: 5),
    Instruction(id: 14, position: (0,0), text: "Bringing your hands down to cup your elbows.", duration: 5),
    Instruction(id: 15, position: (0,0), text: "If you like, you can move a finger gently, exploring this sensation.", duration: 5),
    Instruction(id: 16, position: (0,0), text: "This position is nice because you can use it anywhere, anytime.", duration: 5),
    Instruction(id: 17, position: (0,0), text: "Just give yourself a little squeeze.", duration: 5),
    Instruction(id: 18, position: (0,0), text: "What does it feel like when you support yourself, like a good friend?", duration: 5),
    Instruction(id: 19, position: (0,0), text: "Maybe gently stroking your arms or crossing your arms and giving a gentle squeeze.", duration: 5),
    Instruction(id: 20, position: (0,0), text: "Gently rubbing your chest, or using circular movements.", duration: 5),
    Instruction(id: 21, position: (0,0), text: "Cupping one hand in the other in your lap.", duration: 5),
    Instruction(id: 22, position: (0,0), text: "Bringing your two hands back together, taking a moment to hold your own tummy.", duration: 5),
    Instruction(id: 23, position: (0,0), text: "Maybe your two hands are spread out. Maybe you put one hand over the other.", duration: 5),
    Instruction(id: 24, position: (0,0), text: "You can even approach it like a little game if you like. It doesn't have to be serious.", duration: 5),
    Instruction(id: 25, position: (0,0), text: "Again, just reflecting and noticing what happens in your body when you do this.", duration: 5),
    Instruction(id: 26, position: (0,0), text: "One hand over your chest, over your heart, one hand over your tummy.", duration: 5),
    Instruction(id: 27, position: (0,0), text: "We're just noticing—how do these different forms of touch connect for you?", duration: 5),
    Instruction(id: 28, position: (0,0), text: "What happens in your nervous system, in your body, when you offer yourself a little bit of soothing, supportive touch?", duration: 5),
    Instruction(id: 29, position: (0,0), text: "I want to invite you to practice on your own, and feel free to experiment.", duration: 5),
    Instruction(id: 30, position: (0,0), text: "Use any posture or position that helps you feel calm, and let go of the rest.", duration: 5),
    Instruction(id: 31, position: (0,0), text: "Listen to what your own body tells you.", duration: 5)
]




let topToBottomTexts: [String] = [
    "So now, we're going to practice together.",
        "And please, try to follow along.",
        "Just begin by bringing one hand up to your cheek and cradling your face in your hands.",
        "You can close your eyes if you like, so that you can pay attention to what’s happening in your body.",
        "Just feeling the contact of this hand.",
        "Move your hands up a little bit to your shoulders.",
        "Just resting gently on your shoulders, and notice—how does this feel?",
        "Bring your arms down.",
        "If you like, you can move your hand a little bit, imagining that this person is a human being who needs and deserves understanding and compassion.",
        "Continue by bringing up one of your hands and placing it gently over your heart space.",
        "What does it feel like when you put a hand over your heart?",
        "Now bring up your other hand, placing it on top of the first hand, or next to it if that feels more comfortable.",
        "Just taking a moment to feel these two hands, perhaps imagining that they are caring hands, offering kindness and warmth.",
        "Bringing your hands down to cup your elbows.",
        "If you like, you can move a finger gently, exploring this sensation.",
        "This position is nice because you can use it anywhere, anytime.",
        "Just give yourself a little squeeze.",
        "What does it feel like when you support yourself, like a good friend?",
        "Maybe gently stroking your arms or crossing your arms and giving a gentle squeeze.",
        "Gently rubbing your chest, or using circular movements.",
        "Cupping one hand in the other in your lap.",
        "Bringing your two hands back together, taking a moment to hold your own tummy.",
        "Maybe your two hands are spread out. Maybe you put one hand over the other.",
        "You can even approach it like a little game if you like. It doesn't have to be serious.",
        "Again, just reflecting and noticing what happens in your body when you do this.",
        "One hand over your chest, over your heart, one hand over your tummy.",
        "We're just noticing—how do these different forms of touch connect for you?",
        "What happens in your nervous system, in your body, when you offer yourself a little bit of soothing, supportive touch?",
        "I want to invite you to practice on your own, and feel free to experiment.",
        "Use any posture or position that helps you feel calm, and let go of the rest.",
        "Listen to what your own body tells you."
]

let topToBottomDot: [(Double, Double)] = [
    (0,0),
    (0,0),
 (0.6,0.15),
 (0.6,0.15),
 (0.6,0.15),
 (0.25,0.3),
 (0.25,0.3),
 (0,0),
 (0,0),
    (0.55,0.35),
    (0.55,0.35),
    (0.55,0.35),
    (0.55,0.35),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0),
 (0,0)
]

let bottomToTopTexts: [String] = [
    "So now, we're going to practice together.",
       "And please, try to follow along.",
       "Just begin cupping one hand in the other in your lap.",
       "You can close your eyes if you like, so that you can pay attention to what’s happening in your body.",
       "Just feeling the contact of this hand.",
       "Bringing your two hands back together, taking a moment to hold your own tummy.",
       "Maybe your two hands are spread out. Maybe you put one hand over the other.",
       "Again, just reflecting and noticing what happens in your body when you do this.",
       "Bring up one of your hands and place it gently over your heart space.",
       "One hand over your chest, over your heart, one hand over your tummy.",
       "What does it feel like when you put a hand over your heart?",
       "Now bring up your other hand, and you can place it on top of the first hand or next to it, whichever feels right for you.",
       "Just taking a moment to feel these two hands, perhaps imagining that these are caring hands, offering kindness and warmth.",
       "Move your hands up a little bit to your shoulders.",
       "Just resting gently on your shoulders, and notice—how does this feel?",
       "Bring your arms down.",
       "If you like, you can move your hand a little bit, imagining that this person is a human being who needs and deserves understanding and compassion.",
       "Bringing your hands down to cup your elbows.",
       "Again, moving a finger gently if you like.",
       "This position is nice because you can use it anywhere, anytime.",
       "Just give yourself a little squeeze.",
       "What does it feel like when you support yourself, like a good friend?",
       "Maybe gently stroking your arms or crossing your arms and giving a gentle squeeze.",
       "Gently rubbing your chest, or using circular movements.",
       "Now bring one hand to your cheek, cradling your face in your hands.",
       "We're just noticing—how do these different forms of touch connect for you?",
       "What happens in your nervous system, in your body, when you offer yourself a little bit of soothing, supportive touch?",
       "I want to invite you to practice on your own, and feel free to experiment.",
       "Use any posture or position that helps you feel calm, and let go of the rest.",
       "Listen to what your own body tells you."
]
