import SwiftUI

let topToBottomTexts: [String] = [
    "So now, we're going to practice together.",
    "And please, try to follow along.",
    "Step 1: Cradling the Face",
    "Just begin by bringing one hand up to your cheek and cradling your face in your hands.",
    "You can close your eyes if you like, so that you can pay attention to what’s happening in your body.",
    "Just feeling the contact of this hand.",
    "Step 2: Shoulders",
    "Move your hands up a little bit to your shoulders.",
    "Just resting gently on your shoulders, and notice—how does this feel?",
    "Step 3: Heart Space",
    "Bring your arms down.",
    "If you like, you can move your hand a little bit, imagining that this person is a human being who needs and deserves understanding and compassion.",
    "Continue by bringing up one of your hands and placing it gently over your heart space.",
    "What does it feel like when you put a hand over your heart?",
    "Step 4: Holding the Elbows",
    "Bringing your hands down to cup your elbows.",
    "If you like, you can move a finger gently, exploring this sensation.",
    "This position is nice because you can use it anywhere, anytime—you could be in a meeting, at the office, or even on the SkyTrain.",
    "Just give yourself a little squeeze.",
    "Step 5: Gentle Stroking & Circular Movement",
    "Maybe gently stroking your arms or crossing your arms and giving a gentle squeeze.",
    "Gently rubbing your chest, or using circular movements.",
    "Step 6: Holding the Hands & Tummy",
    "Cupping one hand in the other in your lap.",
    "Bringing your two hands back together, taking a moment to hold your own tummy.",
    "Closing Reflection",
    "We're just noticing—how do these different forms of touch connect for you?",
    "Listen to what your own body tells you."
]

let bottomToTopTexts: [String] = [
    "So now, we're going to practice together.",
    "And please, try to follow along.",
    "Step 1: Cupping Hands in Lap",
    "Just begin cupping one hand in the other in your lap.",
    "You can close your eyes if you like, so that you can pay attention to what’s happening in your body.",
    "Step 2: Holding the Tummy",
    "Bringing your two hands back together, taking a moment to hold your own tummy.",
    "Step 3: Heart Space",
    "Bring up one of your hands and place it gently over your heart space.",
    "One hand over your chest, over your heart, one hand over your tummy.",
    "Step 4: Shoulders & Arms",
    "Move your hands up a little bit to your shoulders.",
    "Just resting gently on your shoulders, and notice—how does this feel?",
    "Step 5: Cradling the Face",
    "Now bring one hand to your cheek, cradling your face in your hands.",
    "Closing Reflection",
    "We're just noticing—how do these different forms of touch connect for you?",
    "Listen to what your own body tells you."
]
